/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSectionRouteImport } from './routes/app.$section'
import { Route as AppFacturacionRouteImport } from './routes/app.facturacion'
import { Route as AppIngresoRouteImport } from './routes/app.ingreso'
import { Route as AppKanbanRouteImport } from './routes/app.kanban'
import { Route as AppProformasRouteImport } from './routes/app.proformas'
import { Route as AppRepuestosRouteImport } from './routes/app.repuestos'
import { Route as AppSegurosRouteImport } from './routes/app.seguros'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSectionRoute = AppSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppRoute,
} as any)
const AppFacturacionRoute = AppFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => AppRoute,
} as any)
const AppIngresoRoute = AppIngresoRouteImport.update({
  id: '/ingreso',
  path: '/ingreso',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppProformasRoute = AppProformasRouteImport.update({
  id: '/proformas',
  path: '/proformas',
  getParentRoute: () => AppRoute,
} as any)
const AppRepuestosRoute = AppRepuestosRouteImport.update({
  id: '/repuestos',
  path: '/repuestos',
  getParentRoute: () => AppRoute,
} as any)
const AppSegurosRoute = AppSegurosRouteImport.update({
  id: '/seguros',
  path: '/seguros',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$section': typeof AppSectionRoute
  '/app/facturacion': typeof AppFacturacionRoute
  '/app/ingreso': typeof AppIngresoRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/repuestos': typeof AppRepuestosRoute
  '/app/seguros': typeof AppSegurosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$section': typeof AppSectionRoute
  '/app/facturacion': typeof AppFacturacionRoute
  '/app/ingreso': typeof AppIngresoRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/repuestos': typeof AppRepuestosRoute
  '/app/seguros': typeof AppSegurosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$section': typeof AppSectionRoute
  '/app/facturacion': typeof AppFacturacionRoute
  '/app/ingreso': typeof AppIngresoRoute
  '/app/kanban': typeof AppKanbanRoute
  '/app/proformas': typeof AppProformasRoute
  '/app/repuestos': typeof AppRepuestosRoute
  '/app/seguros': typeof AppSegurosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$section'
    | '/app/facturacion'
    | '/app/ingreso'
    | '/app/kanban'
    | '/app/proformas'
    | '/app/repuestos'
    | '/app/seguros'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/$section'
    | '/app/facturacion'
    | '/app/ingreso'
    | '/app/kanban'
    | '/app/proformas'
    | '/app/repuestos'
    | '/app/seguros'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$section'
    | '/app/facturacion'
    | '/app/ingreso'
    | '/app/kanban'
    | '/app/proformas'
    | '/app/repuestos'
    | '/app/seguros'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$section': {
      id: '/app/$section'
      path: '/$section'
      fullPath: '/app/$section'
      preLoaderRoute: typeof AppSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/facturacion': {
      id: '/app/facturacion'
      path: '/facturacion'
      fullPath: '/app/facturacion'
      preLoaderRoute: typeof AppFacturacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ingreso': {
      id: '/app/ingreso'
      path: '/ingreso'
      fullPath: '/app/ingreso'
      preLoaderRoute: typeof AppIngresoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kanban': {
      id: '/app/kanban'
      path: '/kanban'
      fullPath: '/app/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proformas': {
      id: '/app/proformas'
      path: '/proformas'
      fullPath: '/app/proformas'
      preLoaderRoute: typeof AppProformasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/repuestos': {
      id: '/app/repuestos'
      path: '/repuestos'
      fullPath: '/app/repuestos'
      preLoaderRoute: typeof AppRepuestosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seguros': {
      id: '/app/seguros'
      path: '/seguros'
      fullPath: '/app/seguros'
      preLoaderRoute: typeof AppSegurosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSectionRoute: typeof AppSectionRoute
  AppFacturacionRoute: typeof AppFacturacionRoute
  AppIngresoRoute: typeof AppIngresoRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppProformasRoute: typeof AppProformasRoute
  AppRepuestosRoute: typeof AppRepuestosRoute
  AppSegurosRoute: typeof AppSegurosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSectionRoute: AppSectionRoute,
  AppFacturacionRoute: AppFacturacionRoute,
  AppIngresoRoute: AppIngresoRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppProformasRoute: AppProformasRoute,
  AppRepuestosRoute: AppRepuestosRoute,
  AppSegurosRoute: AppSegurosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
